### ISSUE TITLE
little issue with the galaxy theme

### ISSUE THREAD

**Issue by phampyk** [JulianPrieber/llc-themes#1]
First of all, thank you so much for all this work.
I was trying to use the galaxy theme but I was having issues with the font. I moved the @import to the top of the skeleton-auto.css and now it loads the font to use.
It's just a little thing but I've been back and forth at it for half an hour lol

**Comment by JulianPrieber** [comment]
**Thank you! I appreciate it.**

Fixed this with: https://github.com/JulianPrieber2/galaxy/commit/ac1ab92f72c1f74fc3227f741198d1bc8a837ec6.
Thank you very much for pointing this out.
