### ISSUE TITLE
PaperBold theme

### ISSUE THREAD

**Issue by nekosheen** [JulianPrieber/llc-themes#12]
Hey I'd like to submit [PaperBold](https://github.com/nekosheen/PaperBold) for the list of official themes 👍🏽

**Comment by JulianPrieber** [comment]
Thank you for contributing!

**Comment by JulianPrieber** [comment]
Your themes have been added.
Two of the themes return an error on the theme updater, I think that's because the releases are marked as pre-release.
This won't affect your theme in any way, but may confuse some people who download it.

**Comment by JulianPrieber** [comment]
If you want to update any details about your themes, you can open a pull request. We use this file for our API:
https://github.com/LinkStackOrg/linkstack-themes/blob/main/themes.json#L264-L300
