### ISSUE TITLE
Repo for Aurora theme

### ISSUE THREAD

**Issue by MagicLike** [JulianPrieber/llc-themes#2]
Is there a repo available for the Aurora theme?

**Comment by JulianPrieber** [comment]
Nope, this one was made by a user on our Discord who's apparently not very comfortable working with GitHub.

The thing is still hosted on one of our servers, so I can still apply updates this way: https://update.littlelink-custom.com/themes/

**Comment by MagicLike** [comment]
Ok, thank you.
I already searched it for Google Fonts - nothing found, so no need to update... xD

**Comment by JulianPrieber** [comment]
ou
